<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MaxMessenger.Bot" Version="0.6.2-alpha" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NivoMaxBot.Messaging\NivoMaxBot.Messaging.csproj" />
  </ItemGroup>

</Project>
