<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="appsettings.json" />
    <None Remove="MenuPhotos\catalog_root.jpg" />
    <None Remove="MenuPhotos\main_menu.jpg" />
    <None Remove="Resources\about_brand.mp4" />
    <None Remove="Resources\Advantages\advantage_support.jpg" />
    <None Remove="Resources\brand_data.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="MenuPhotos\catalog_root.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="MenuPhotos\main_menu.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Advantages\advantage_support.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.8" />
    <PackageReference Include="Scrutor" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NivoMaxBot.Application\NivoMaxBot.Application.csproj" />
    <ProjectReference Include="..\NivoMaxBot.Infrastructure\NivoMaxBot.Infrastructure.csproj" />
    <ProjectReference Include="..\NivoMaxBot.MaxMessaging\NivoMaxBot.MaxMessaging.csproj" />
    <ProjectReference Include="..\NivoMaxBot.Messaging\NivoMaxBot.Messaging.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\brand_data.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\about_brand.mp4">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
